apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: sb9y9ps12-nodejs 
  janus-idp.io/tekton: sb9y9ps12-nodejs
  backstage.io/kubernetes-id: sb9y9ps12-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: sb9y9ps12-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml